#!/usr/bin/env python3
"""Gap-fill: scrape a single ASIN and write briefing."""
import sys, os, json
from datetime import datetime
from apify_client import ApifyClient

WORKSPACE = os.path.expanduser("~/.openclaw/workspace")
CONFIG = os.path.join(WORKSPACE, "theshoppersverdict/scripts/.apify_config.json")
BRIEFINGS_DIR = os.path.join(WORKSPACE, "theshoppersverdict/briefings")
TOKEN = json.load(open(CONFIG))["apify_token"]
client = ApifyClient(TOKEN)

# Praise/complaint detection
PRAISE = {'Quality': ['quality','well made','durable','sturdy','solid','premium'],
          'Value': ['value','worth','price','affordable','reasonable'],
          'Ease of Use': ['easy','simple','intuitive','convenient','user-friendly'],
          'Performance': ['fast','quick','powerful','efficient','effective','great'],
          'Design': ['beautiful','sleek','modern','stylish','design','compact']}
COMPLAINTS = {'Quality Issues': ['cheap','flimsy','broke','defective','poor quality','stopped'],
             'Difficult to Use': ['complicated','confusing','difficult','frustrating'],
             'Poor Performance': ['slow','weak','ineffective','disappointing'],
             'Design Flaws': ['noisy','bulky','heavy','awkward'],
             'Support': ['warranty','return','refund','support','customer service']}

def analyze(reviews):
    pc = {k:0 for k in PRAISE}
    cc = {k:0 for k in COMPLAINTS}
    for t in reviews:
        tl = t.lower()
        for k,v in PRAISE.items():
            for w in v:
                if w in tl: pc[k] += 1; break
        for k,v in COMPLAINTS.items():
            for w in v:
                if w in tl: cc[k] += 1; break
    return pc, cc

def make_briefing(asin, title, price, rating, review_count, image_url, items):
    reviews = [r.get('reviewDescription','') or '' for r in items]
    praise, comp = analyze(reviews) if reviews else ({}, {})
    total = max(len(reviews), 1)
    lines = []
    lines.append(f'# Product Briefing: {title}')
    lines.append('')
    lines.append(f'**ASIN:** {asin}  |  **Date:** {datetime.now().strftime("%Y-%m-%d")}')
    lines.append('')
    lines.append('## Quick Stats')
    lines.append('')
    lines.append('| Field | Value |')
    lines.append('|-------|-------|')
    lines.append(f'| Price | ${price}' if price else '| Price | N/A |')
    if rating: lines.append(f'| Rating | {rating}/5 ⭐ |')
    if review_count: lines.append(f'| Reviews Analyzed | {review_count:,} total, {total} sampled |')
    if image_url: lines.append(f'| Image | {image_url} |')
    lines.append('')

    if any(v > 0 for v in praise.values()):
        lines.append('## Top Praise Themes')
        lines.append('')
        for k,v in sorted(praise.items(), key=lambda x: x[1], reverse=True):
            if v > 0:
                bars = '█' * min(v * 3, 30)
                lines.append(f'- **{k}:** {bars} ({v}/{total})')
        lines.append('')

    if any(v > 0 for v in comp.values()):
        lines.append('## Top Complaint Themes')
        lines.append('')
        for k,v in sorted(comp.items(), key=lambda x: x[1], reverse=True):
            if v > 0:
                bars = '█' * min(v * 3, 30)
                lines.append(f'- **{k}:** {bars} ({v}/{total})')
        lines.append('')

    lines.append('## Review Samples')
    lines.append('')
    for i, r in enumerate(items[:5], 1):
        text = r.get('reviewDescription','') or ''
        rtitle = r.get('reviewTitle','') or ''
        rtg = r.get('ratingScore','?')
        dt = r.get('date','')
        lines.append(f'**{i}. [{rtg}/5] {dt}** — {rtitle}')
        lines.append(f'> {text[:300]}{"..." if len(text) > 300 else ""}')
        lines.append('')

    lines.append('---')
    lines.append(f'*Briefing generated by Scout 🕵️ via Apify on {datetime.now().strftime("%Y-%m-%d %H:%M")}*')
    return '\n'.join(lines)

def scrape(asin):
    url = f'https://www.amazon.com/dp/{asin}'
    print(f'[SCAN] {asin}...', end=' ', flush=True)
    run = client.actor('R8WeJwLuzLZ6g4Bkk').call(run_input={
        'productUrls': [{'url': url}],
        'maxReviews': 8,
        'sort': 'helpful',
        'scrapeProductDetails': True,
    }, timeout_secs=90)
    dataset_id = run['defaultDatasetId']
    items = list(client.dataset(dataset_id).iterate_items())
    if not items:
        print('❌ empty')
        return None
    p = items[0].get('product', {})
    title = p.get('title', 'Unknown Product')
    price_val = p.get('price')
    if isinstance(price_val, dict): price = price_val.get('value')
    elif isinstance(price_val, (int, float)): price = float(price_val)
    else: price = None
    stars_raw = p.get('stars', '')
    rating = float(str(stars_raw).split()[0]) if stars_raw else None
    review_count = p.get('reviewsCount', None)
    hi_res = p.get('highResolutionImages', [])
    image_url = hi_res[0] if hi_res else p.get('thumbnailImage', '')
    print(f'✅ {title[:40]}')
    return {'asin': asin, 'title': title, 'price': price, 'rating': rating,
            'review_count': review_count, 'image_url': image_url, 'items': items}

if __name__ == '__main__':
    asin = sys.argv[1]
    result = scrape(asin)
    if not result:
        print(f"❌ Failed to scrape {asin}")
        sys.exit(1)
    briefing = make_briefing(
        result['asin'], result['title'], result['price'],
        result['rating'], result['review_count'],
        result['image_url'], result['items']
    )
    os.makedirs(BRIEFINGS_DIR, exist_ok=True)
    fpath = os.path.join(BRIEFINGS_DIR, f'{asin}_briefing.md')
    with open(fpath, 'w') as f:
        f.write(briefing)
    print(f"✅ {fpath}")
