#!/usr/bin/env python3
"""
Scout 🕵️ — Apify-powered Amazon Review Scout
Usage: python3 scout_apify.py <ASIN_or_URL>
"""

import sys, os, re
from datetime import datetime
from apify_client import ApifyClient

import json; API_TOKEN = json.load(open(os.path.join(os.path.dirname(__file__), ".apify_config.json")))["apify_token"]

def extract_asin(text):
    m = re.search(r'/(?:dp|product)/([A-Z0-9]{10})', text)
    if m: return m.group(1)
    m = re.search(r'(B[A-Z0-9]{9})\b', text)
    if m: return m.group(1)
    return None

def analyze_sentiment(reviews):
    praise = {'Quality': ['quality','well made','durable','sturdy','solid','premium'],
              'Value': ['value','worth','price','affordable','reasonable'],
              'Ease of Use': ['easy','simple','intuitive','convenient','user-friendly'],
              'Performance': ['fast','quick','powerful','efficient','effective','great'],
              'Design': ['beautiful','sleek','modern','stylish','design','compact']}
    complaints = {'Quality Issues': ['cheap','flimsy','broke','defective','poor quality','stopped'],
                 'Difficult to Use': ['complicated','confusing','difficult','frustrating'],
                 'Poor Performance': ['slow','weak','ineffective','disappointing'],
                 'Design Flaws': ['noisy','bulky','heavy','awkward'],
                 'Support': ['warranty','return','refund','support','customer service']}
    pc = {k:0 for k in praise}
    cc = {k:0 for k in complaints}
    for r_text in reviews:
        rl = r_text.lower()
        for k,v in praise.items():
            for w in v:
                if w in rl: pc[k] += 1; break
        for k,v in complaints.items():
            for w in v:
                if w in rl: cc[k] += 1; break
    return pc, cc

def generate_briefing(asin, title, price, rating, review_count, image_url, reviews_data):
    reviews = [r.get('reviewDescription','') or '' for r in reviews_data]
    praise, complaints = analyze_sentiment(reviews) if reviews else ({}, {})
    
    total = len(reviews)
    
    lines = []
    lines.append(f'# Product Briefing: {title}')
    lines.append('')
    lines.append(f'**ASIN:** {asin}  |  **Date:** {datetime.now().strftime("%Y-%m-%d")}')
    lines.append('')
    if image_url:
        lines.append(f'![Product]({image_url})')
        lines.append('')
    
    lines.append('## Quick Stats')
    lines.append('')
    lines.append('| Field | Value |')
    lines.append('|-------|-------|')
    lines.append(f'| Price | ${price} |' if price else '| Price | N/A |')
    if rating: lines.append(f'| Rating | {rating}/5 ⭐ |')
    if review_count: lines.append(f'| Reviews Analyzed | {review_count:,} total, {total} sampled |')
    if image_url: lines.append(f'| Image | {image_url} |')
    lines.append('')
    
    if any(v > 0 for v in praise.values()):
        lines.append('## Top Praise Themes')
        lines.append('')
        for k,v in sorted(praise.items(), key=lambda x: x[1], reverse=True):
            if v > 0:
                bars = '█' * min(v * 3, 30)
                lines.append(f'- **{k}:** {bars} ({v}/{total})')
        lines.append('')
    
    if any(v > 0 for v in complaints.values()):
        lines.append('## Top Complaint Themes')
        lines.append('')
        for k,v in sorted(complaints.items(), key=lambda x: x[1], reverse=True):
            if v > 0:
                bars = '█' * min(v * 3, 30)
                lines.append(f'- **{k}:** {bars} ({v}/{total})')
        lines.append('')
    
    lines.append('## Review Samples')
    lines.append('')
    for i, r in enumerate(reviews_data[:5], 1):
        text = r.get('reviewDescription','') or ''
        title_text = r.get('reviewTitle','') or ''
        rating = r.get('ratingScore','?')
        date = r.get('date','')
        lines.append(f'**{i}. [{rating}/5] {date}** — {title_text}')
        lines.append(f'> {text[:300]}{"..." if len(text) > 300 else ""}')
        lines.append('')
    
    lines.append('---')
    lines.append(f'*Briefing generated by Scout 🕵️ via Apify on {datetime.now().strftime("%Y-%m-%d %H:%M")}*')
    
    return '\n'.join(lines)

def main():
    if len(sys.argv) < 2:
        print('Usage: python3 scout_apify.py <ASIN_or_URL>')
        sys.exit(1)
    
    asin = extract_asin(sys.argv[1])
    if not asin:
        print('ERROR: No ASIN found in:', sys.argv[1])
        sys.exit(1)
    
    url = f'https://www.amazon.com/dp/{asin}'
    print(f'[SCOUT] Fetching reviews for {url}...')
    
    client = ApifyClient(API_TOKEN)
    run = client.actor('R8WeJwLuzLZ6g4Bkk').call(run_input={
        'productUrls': [{'url': url}],
        'maxReviews': 10,
        'sort': 'helpful',
        'scrapeProductDetails': True,
    })
    
    dataset_id = run['defaultDatasetId']
    items = list(client.dataset(dataset_id).iterate_items())
    
    if not items:
        print('ERROR: No data returned')
        sys.exit(1)
    
    p = items[0].get('product', {})
    title = p.get('title', 'Unknown Product')
    # Apify price may be dict {value: ...} or direct int/float
    price_val = p.get('price')
    if isinstance(price_val, dict):
        price = price_val.get('value')
    elif isinstance(price_val, (int, float)):
        price = float(price_val)
    else:
        price = None
    # Stars may be string "4.7 out of 5 stars" or direct float 4.7
    stars_raw = p.get('stars', '')
    if stars_raw is None: stars_raw = ''
    rating = float(str(stars_raw).split()[0]) if stars_raw else None
    review_count = p.get('reviewsCount', None)
    # Apify returns images under highResolutionImages or thumbnailImage key
    hi_res = p.get('highResolutionImages', [])
    image_url = hi_res[0] if hi_res else None
    if not image_url:
        thumb = p.get('thumbnailImage', '')
        if thumb:
            image_url = thumb
    
    print(f'\n{"="*60}')
    print(f'📦 {title}')
    print(f'{"="*60}')
    print(f'   Price:     ${price}' if price else '   Price:     N/A')
    print(f'   Rating:    {rating}/5 ⭐' if rating else '   Rating:    N/A')
    print(f'   Reviews:   {review_count:,} total' if review_count else '   Reviews:   N/A')
    print(f'   Sampled:   {len(items)} reviews')
    print(f'{"="*60}\n')
    
    briefing = generate_briefing(asin, title, price, rating, review_count, image_url, items)
    
    briefing_dir = os.path.expanduser("~/.openclaw/workspace/theshoppersverdict/briefings")
    os.makedirs(briefing_dir, exist_ok=True)
    fpath = os.path.join(briefing_dir, f'{asin}_briefing.md')
    with open(fpath, 'w') as f:
        f.write(briefing)
    
    print(f'[SCOUT] Briefing saved: {fpath}')
    print()

if __name__ == '__main__':
    main()
